# Generated by Django 5.1.2 on 2025-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSMEOrderingWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='force_closed',
            field=models.BooleanField(default=False),
        ),
    ]
